// Mock data for development - will be replaced by API calls
export const mockProducts = [
  {
    id: '1',
    title: 'Premium Wireless Headphones',
    price: 299.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    rating: 4.5,
    reviews: 1250,
    description: 'Experience crystal-clear audio with our premium wireless headphones. Featuring active noise cancellation and 30-hour battery life.',
    category: 'Electronics',
    inStock: true,
  },
  {
    id: '2',
    title: 'Smart Watch Pro',
    price: 399.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    rating: 4.8,
    reviews: 2100,
    description: 'Stay connected with our advanced smartwatch. Track your fitness, receive notifications, and more.',
    category: 'Electronics',
    inStock: true,
  },
  {
    id: '3',
    title: 'Leather Backpack',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
    rating: 4.6,
    reviews: 890,
    description: 'Premium leather backpack with multiple compartments. Perfect for work or travel.',
    category: 'Fashion',
    inStock: true,
  },
  {
    id: '4',
    title: 'Running Shoes Elite',
    price: 179.99,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    rating: 4.7,
    reviews: 1560,
    description: 'Professional running shoes with advanced cushioning technology.',
    category: 'Sports',
    inStock: true,
  },
  {
    id: '5',
    title: 'Coffee Maker Deluxe',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500&h=500&fit=crop',
    rating: 4.4,
    reviews: 670,
    description: 'Brew the perfect cup every morning with programmable settings.',
    category: 'Home',
    inStock: true,
  },
  {
    id: '6',
    title: 'Yoga Mat Premium',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop',
    rating: 4.6,
    reviews: 450,
    description: 'Extra thick yoga mat with non-slip surface for ultimate comfort.',
    category: 'Sports',
    inStock: true,
  },
  {
    id: '7',
    title: 'Designer Sunglasses',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop',
    rating: 4.5,
    reviews: 320,
    description: 'UV protection with style. Premium polarized lenses.',
    category: 'Fashion',
    inStock: true,
  },
  {
    id: '8',
    title: 'Gaming Mouse RGB',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=500&h=500&fit=crop',
    rating: 4.7,
    reviews: 980,
    description: 'High-precision gaming mouse with customizable RGB lighting.',
    category: 'Electronics',
    inStock: true,
  },
];

export const mockOrders = [
  {
    id: 'ORD-001',
    date: '2024-01-15',
    total: 299.99,
    status: 'Delivered',
    items: [
      {
        id: '1',
        title: 'Premium Wireless Headphones',
        quantity: 1,
        price: 299.99,
      },
    ],
  },
  {
    id: 'ORD-002',
    date: '2024-01-20',
    total: 549.98,
    status: 'In Transit',
    items: [
      {
        id: '2',
        title: 'Smart Watch Pro',
        quantity: 1,
        price: 399.99,
      },
      {
        id: '3',
        title: 'Leather Backpack',
        quantity: 1,
        price: 149.99,
      },
    ],
  },
];

export const mockViewHistory = mockProducts.slice(0, 4);
